name: v1.0 - CLI Tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv shell
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Test with nose2
        run: nose2
      - run: echo "This job's status is ${{ job.status }}."
